### ISSUE TITLE
The package cannot be installed with the python3.6

### ISSUE THREAD

**Issue by Hax0rG1rl** [trolldbois/python3-adns#1]
Hi, 

I'm trying to use pip and get this library installed for python 3.6. However, I do get this error message:

```
pip3.6 install --user adns
Collecting adns
  Could not find a version that satisfies the requirement adns (from versions: 1.4-py0)
No matching distribution found for adns
```

Any ideas how can I have it installed by using the pip way or should I simply try to compile it from the source(less ideal though)? 

Thanks.

**Comment by ZhepuZhao** [comment]
Got the same issue. Did you fix the problem yet?

**Comment by Hax0rG1rl** [comment]
Nope :(

**Comment by ZhepuZhao** [comment]
Just solved it with the help of my colleagues. Try to install `libadns1-dev` and `adns-tools` on your system first(I used ansible to do that for convenience, but basically you can use apt to install it), then if you are using venv, `pip install adns` or `pip3 install adns` depending on your python version. Seems like you're using python3

**Comment by Hax0rG1rl** [comment]
That's sweet. Thanks so much!
