### ISSUE TITLE
Custom-built wheel cannot be installed because version number doesn't comply with PEP440

### ISSUE THREAD

**Issue by PLPeeters** [trolldbois/python3-adns#2]
I'm in a setup where I'm building the wheel and saving it to a local index to reuse it later, and that isn't possible with the new resolver because the current version isn't compliant with [PEP440](https://peps.python.org/pep-0440/). The resolver refuses to consider the wheel from my index when resolving:

```
pip._vendor.packaging.version.InvalidVersion: Invalid version: '1.4-py0'
```

More info here: https://github.com/pypa/pip/issues/9188

For now, I fell back to the legacy resolver, but this is probably going to break sooner or later, so could you please upload a version that is compliant, i.e. not postfixed with `-py[0-9]`?

Thanks!

**Comment by PLPeeters** [comment]
@trolldbois This is going to break soon.

> DEPRECATION: adns 1.4-py0 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of adns or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by trolldbois** [comment]
fixed
